'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../mission-sar-search-core.js'),scene=require('../mission-sar-scene-core.js'),runtime=require('./tracker-mission-poi-runtime.js'),fixture=require('./tracker-mission-sar-fixture.js'),task=require('./tracker-mission-sar-task.js');
const center={lat:48.3,lon:8.5};
function scenario(truth='incident'){return {schema:'sar-search.v2',center,radiusNm:1.5,minSearchSec:180,maxSearchSec:600,truth,pending:false,...(truth==='incident'?{source:{id:'one',lat:center.lat+.006,lon:center.lon,label:'ein Fahrzeug abseits der Straße',altFt:940},scenePrimaryFeature:'road_vehicles',scenePlan:{kind:'road_incident',requirements:[{feature:'road_vehicles',count:1,forwardM:.006*111320,rightM:0}]}}:{})};}
function sample(s,now,patch={}){return {observedAt:now,lat:s.source?.lat||center.lat,lon:s.source?.lon||center.lon,onGround:false,altFt:3000,gsKts:85,...patch};}
function bundle(truth){const b=fixture.bundle(),r=b.executionPoiRecipe;r.version=2;r.sarScenario=scenario(truth);r.target=center;r.passenger.targetRadiusNm=1.5;r.voiceContext.passenger.targetRadiusNm=1.5;const source=r.sarScenario.source||center;r.sarReport.confirmCoords={lat:source.lat,lon:source.lon};r.voiceContext.sarReport=structuredClone(r.sarReport);if(truth!=='no_contact')b.executionEffectPlan.effects['scene.target']={command:{type:'mission_scene_spawn',sceneId:'sar-target',...center,altFt:940,hdg:0,items:[{kind:'sar_road_vehicles_0',forwardM:.006*111320,rightM:0}]}};else b.executionEffectPlan.effects['scene.target']={none:true};return b;}
function geometry(){const p=(x,y)=>({lon:center.lon+x/(111320*Math.cos(center.lat*Math.PI/180)),lat:center.lat+y/111320}),ring=(x1,y1,x2,y2)=>[p(x1,y1),p(x2,y1),p(x2,y2),p(x1,y2),p(x1,y1)];return {elements:[{type:'way',id:1,tags:{landuse:'meadow'},geometry:ring(-2000,-2000,2000,2000)},{type:'way',id:2,tags:{highway:'secondary',name:'Teststraße'},geometry:[p(-1500,600),p(1500,600)]},{type:'way',id:3,tags:{natural:'water'},geometry:ring(800,800,1200,1200)},{type:'way',id:4,tags:{building:'yes'},geometry:ring(-1200,800,-800,1200)}]};}
test('actual roadside candidates and all object offsets are checked against mapped surfaces',()=>{const geo=scene.geometry(geometry(),center);assert.ok(geo.sarCandidates.some(p=>p.incident==='road_vehicle'));assert.ok(geo.sarCandidates.some(p=>p.incident==='missing_hiker'));assert.ok(scene.candidateError({x:1000,y:1000},'missing_hiker',geo));assert.ok(scene.candidateError({x:-1000,y:1000},'missing_hiker',geo));assert.ok(scene.candidateError({x:600,y:0},'road_vehicle',geo));const c=geo.sarCandidates.find(p=>p.incident==='road_vehicle');const raw={kind:'road_incident',requirements:[{feature:'small_equipment',count:1,forwardM:c.y+10,rightM:c.x},{feature:'road_vehicles',count:1,forwardM:c.y,rightM:c.x}]};const accepted=scene.accept(raw,{incident:'road_vehicle'},geo);assert.ok(accepted);assert.equal(accepted.scene.requirements[0].feature,'road_vehicles');assert.ok(core.distance(center,accepted.source)>.12);raw.requirements[0].forwardM=c.y;assert.equal(scene.accept(raw,{incident:'road_vehicle'},geo),null);});
test('near observation accelerates detection but completing requires separate assessment and minimum search time',()=>{const s=scenario();let state=core.create(s),voices=[];for(let now=0;now<=185000;now+=1000){const r=core.observe(s,state,sample(s,now),now);state=r.state;voices.push(...r.voices);}assert.equal(state.complete,true);assert.equal(state.outcome,'contact_reported');assert.equal(voices.filter(v=>v.label==='Sichtkontakt').length,1);assert.equal(voices.filter(v=>v.label==='Suchabschluss').length,1);assert.ok(state.assessmentSec>=30);assert.equal(core.project(s,core.create(s)).searchArea.findings.length,0);assert.ok(!JSON.stringify(core.project(s,core.create(s))).includes('ein Fahrzeug'));});
test('late discovery does not authorize immediate return; a report button cannot fabricate a finding',()=>{const b=bundle(),r=b.executionPoiRecipe;let state=runtime.createState(r);state.sarSearchState.observedSec=190;const result=task.action(r,state,sample(r.sarScenario,1000),1000);assert.equal(result.poiTask.detector.satisfied,false);assert.equal(result.poiTask.sarSearchState.found,null);state=core.create(r.sarScenario);state.observedSec=190;for(let now=0;now<=6000;now+=1000)state=core.observe(r.sarScenario,state,sample(r.sarScenario,now),now).state;assert.ok(state.found);assert.equal(state.complete,false);});
test('offline pause, outside and paused samples cannot earn evidence; no-contact finishes without invented rescue',()=>{const s=scenario('no_contact');let state=core.create(s);state=core.observe(s,state,sample(s,0),0).state;core.pause(state);state=core.observe(s,state,sample(s,100000),100000).state;assert.equal(state.observedSec,0);for(let now=101000;now<=705000;now+=1000)state=core.observe(s,state,sample(s,now),now).state;assert.equal(state.complete,true);assert.equal(state.found,null);assert.equal(state.outcome,'no_contact');assert.match(core.summary(state).text,/keinen belastbaren/);});
test('SAR version and scene-source consistency fail closed; legacy recipes continue unchanged',()=>{assert.equal(runtime.validateBundle(fixture.bundle()),null);const b=bundle();assert.equal(runtime.validateBundle(b),null);b.executionPoiRecipe.version=1;assert.equal(runtime.validateRecipe(b.executionPoiRecipe),'sar_search_version_required');b.executionPoiRecipe.version=2;b.executionEffectPlan.effects['scene.target'].command.items[0].rightM=100;assert.equal(runtime.validateBundle(b),'sar_scene_source_mismatch');assert.equal(runtime.validateBundle(bundle('no_contact')),null);});
test('tracker projection shows circle from preparation; pause and unavailable equipment stop search',()=>{const r=bundle().executionPoiRecipe;let state=runtime.createState(r);assert.equal(runtime.project(state).sarSearch.searchArea.radiusM,2778);for(let now=0;now<10000;now+=1000){state=runtime.observe(r,state,sample(r.sarScenario,now),{active:true,trackingActive:true,taskItemState:{blockingItems:['Fernglas']}}).state;}assert.equal(state.sarSearchState.observedSec,0);});

test('aircraft candidates require open land; boat candidates reject shores and island holes',()=>{
 const geo=scene.geometry(geometry(),center);assert.ok(geo.sarCandidates.some(p=>p.incident==='missing_aircraft'));assert.ok(geo.sarCandidates.some(p=>p.incident==='overdue_boat'));
 const boat=geo.sarCandidates.find(p=>p.incident==='overdue_boat');assert.equal(scene.candidateError(boat,'overdue_boat',geo),'');assert.ok(scene.candidateError({x:0,y:600},'overdue_boat',geo));
 geo.waterHoles=[[{x:900,y:900},{x:1100,y:900},{x:1100,y:1100},{x:900,y:1100},{x:900,y:900}]];assert.equal(scene.candidateError({x:1000,y:1000},'overdue_boat',geo),'sar_water_invalid');
 geo.shapes.push({type:'forest',closed:true,blocked:true,buffer:0,points:[{x:500,y:900},{x:700,y:900},{x:700,y:1100},{x:500,y:1100},{x:500,y:900}]});assert.ok(scene.candidateError({x:600,y:1000},'missing_aircraft',geo));
});

test('manual status and orientation stay tied to public search progress, never legacy random outcomes',()=>{
 const r=bundle().executionPoiRecipe,state=runtime.createState(r),adapter=require('./tracker-mission-sar-search-task.js');
 const pending=adapter.statusCue(r,state,'poi_status',1000);assert.match(pending.resolvedRecipe.fallbackText,/kein belastbarer/);assert.ok(!JSON.stringify(pending).includes(r.sarScenario.source.lat.toString()));
 state.sarSearchState.found={id:'one',lat:r.sarScenario.source.lat,lon:r.sarScenario.source.lon};assert.match(adapter.statusCue(r,state,'poi_status',2000).resolvedRecipe.fallbackText,/Sichtkontakt.*gemeldet/);
 assert.match(adapter.statusCue(r,state,'poi_orientation',3000).resolvedRecipe.fallbackText,/feste Bezugspunkt/);
});

test('late Leitstelle hint is coarse, independent of aircraft proximity, once only and never after contact',()=>{
 const s=scenario();s.source.lon=center.lon-.02;s.source.lat=center.lat;
 let state=core.create(s),messages=[];
 for(let now=0;now<=190000;now+=1000){const r=core.observe(s,state,{...center,onGround:false},now);state=r.state;messages.push(...r.voices);}
 const hints=messages.filter(v=>v.label==='Suchhinweis');assert.equal(hints.length,1);assert.match(hints[0].text,/Leitstelle.*westlich des Referenzpunktes/);assert.doesNotMatch(hints[0].text,/\d|Meilen|Grad|nordwest/);
 state=core.create(s);state.found={id:'one'};state.observedSec=180;assert.equal(core.observe(s,state,{...center,onGround:false},1000).voices.some(v=>v.label==='Suchhinweis'),false);
 assert.equal(core.hint(scenario('no_contact')),null);
});
