const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function fixture(){let now=1,seq=0;const timers=new Map(),listeners={},requests=[],frames=[];const node=()=>({style:{},addEventListener(){},querySelector(){return null;},getAttribute(){return ''}});const nodes=Object.fromEntries(['VfrMultitoolPanel','vfr-frame-container','vfr-status','vfr-offline','vfr-statusbar','vfr-retry','vfr-close'].map(id=>[id,node()]));Object.assign(nodes.VfrMultitoolPanel,{active:true,visible:true,minimized:false});Object.assign(nodes['vfr-frame-container'],{appendChild(f){frames.push(f)},removeChild(f){frames.splice(frames.indexOf(f),1)}});const window={addEventListener(n,f){listeners[n]=f},requestAnimationFrame(){return ++seq},cancelAnimationFrame(){}};const document={hidden:false,getElementById:id=>nodes[id],addEventListener(){},createElement(){return {contentWindow:{postMessage(){}},style:{}}}};class XHR{constructor(){requests.push(this)}open(){}send(){}abort(){this.aborted=true}}
vm.runInNewContext(fs.readFileSync(__dirname+'/PackageSources/html_ui/InGamePanels/VfrMultitool/Panel.js','utf8'),{window,document,XMLHttpRequest:XHR,MutationObserver:class{observe(){}},Date:{now:()=>now},Math,console:{log(){}},setTimeout(fn){const id=++seq;timers.set(id,fn);return id},clearTimeout(id){timers.delete(id)}});
return {nodes,frames,requests,advance(ms=4000){now+=ms;const [id,fn]=timers.entries().next().value;timers.delete(id);fn()},reply(session='a',ok=true){const xhr=requests.at(-1);xhr.status=ok?200:503;xhr.responseText=JSON.stringify({message:{payload:{viewSessionId:session}}});xhr.onload()},ready(){const f=frames[0],channel=new URL(f.src).searchParams.get('channel');listeners.message({data:{type:'ga-efb-kartentisch',state:'ready',channel},source:f.contentWindow,origin:'http://127.0.0.1:49880'})}};
}
test('toolbar retains brief outages, unloads sustained outages and reconnects automatically',()=>{const f=fixture();f.reply();f.ready();const first=f.frames[0];f.advance();f.reply('',false);assert.equal(f.frames[0],first);f.advance();f.reply('',false);assert.equal(f.frames.length,0);f.advance();f.reply();assert.equal(f.frames.length,1);assert.notEqual(f.frames[0],first);f.ready();assert.equal(f.nodes['vfr-offline'].style.display,'none')});
test('tracker session change recreates the child even without a failed request',()=>{const f=fixture();f.reply('a');f.ready();const first=f.frames[0];f.advance();f.reply('b');assert.equal(f.frames.length,1);assert.notEqual(f.frames[0],first)});
test('readiness timeout does not stop recovery polling',()=>{const f=fixture();f.reply();const first=f.frames[0];f.advance(21000);assert.equal(f.frames.length,0);f.reply();assert.equal(f.frames.length,1);assert.notEqual(f.frames[0],first)});
test('late requests from a suspended panel cannot restore an iframe',()=>{const f=fixture();const pending=f.requests[0];f.nodes['vfr-retry'].onclick();pending.status=200;pending.onload();assert.equal(f.frames.length,0);f.reply();assert.equal(f.frames.length,1)});
