import test from 'node:test';import assert from 'node:assert/strict';import {parseFaaAirportHtml,handleAirportContextFaa} from './airport-context-faa.mjs';
const now=Date.parse('2026-10-07T12:00Z'),html=`Data Effective: <strong>10/01/2026 - 10/29/2026</strong><div id="constructionNoticeDiv" hidden>ACTIVE CONSTRUCTION</div><div class="tab-pane active" id="summary"><table><tr><td>Latitude/Longitude</td><td>45-7-59.675 N / 115-19-18.404 W</td></tr></table></div><div class="tab-pane" id="operations"><table><tr><td>Fuel</td><td>NONE</td></tr></table></div><div class="tab-pane" id="remarks"><ul><li>NO WINTER MAINTENANCE.</li><li>TREES &amp; ANIMALS.</li></ul></div><script>var locationId = "U60";</script>`;
const req=id=>new Request('https://ga-proxy.invalid/api/airport-context/faa?ident='+id);
test('FAA parser verifies identity/position/cycle and excludes hidden construction placeholder',()=>{const v=parseFaaAirportHtml(html,'U60',now);assert.ok(Math.abs(v.lat-45.133243)<.00001);assert.equal(v.remarks[1],'TREES & ANIMALS.');assert.ok(!JSON.stringify(v).includes('ACTIVE CONSTRUCTION'));assert.throws(()=>parseFaaAirportHtml(html,'U61',now),/identity/);assert.throws(()=>parseFaaAirportHtml(html,'U60',Date.parse('2026-12-01')),/not_current/);});
test('narrow route rejects arbitrary URLs without upstream requests',async()=>{let calls=0;const v=await handleAirportContextFaa(req(encodeURIComponent('https://evil.invalid')), {fetcher:()=>calls++});assert.equal(v.status,400);assert.equal(calls,0);});
test('successful fetch uses a fixed host and returns only parsed data',async()=>{let url;const r=await handleAirportContextFaa(req('u60'),{now,cache:null,fetcher:async (v,options)=>{url=v;assert.equal(options.redirect,'manual');return new Response(html);}});assert.equal(r.status,200);assert.match(url,/^https:\/\/nfdc.faa.gov\//);assert.equal((await r.json()).ident,'U60');});
test('deadline holds when upstream ignores AbortSignal',async()=>{const began=Date.now(),r=await handleAirportContextFaa(req('U60'),{now,cache:null,timeoutMs:35,fetcher:()=>new Promise(()=>{})});assert.equal(r.status,504);assert.ok(Date.now()-began<180);});
test('upstream status/oversize are optional failures and never cached',async()=>{let puts=0;for(const value of [new Response('gone',{status:404}),new Response('x'.repeat(256001))]){const r=await handleAirportContextFaa(req('U60'),{now,cache:{match:async()=>null,put:async()=>puts++},fetcher:async()=>value});assert.equal(r.status,502);}assert.equal(puts,0);});
test('valid cached cycle avoids network; expired cycle refetches',async()=>{let calls=0;const data=parseFaaAirportHtml(html,'U60',now),cache={match:async()=>new Response(JSON.stringify(data)),put:async()=>{}};assert.equal((await handleAirportContextFaa(req('U60'),{now,cache,fetcher:async()=>{calls++;return new Response(html);}})).status,200);assert.equal(calls,0);await handleAirportContextFaa(req('U60'),{now:Date.parse('2026-11-01'),cache,fetcher:async()=>{calls++;return new Response(html);}});assert.equal(calls,1);});

test('upstream redirect is never followed or cached',async()=>{let calls=0,puts=0;const r=await handleAirportContextFaa(req('U60'),{now,cache:{match:async()=>null,put:async()=>puts++},fetcher:async (_,options)=>{calls++;assert.equal(options.redirect,'manual');return new Response(null,{status:302,headers:{Location:'https://other.invalid/'}});}});assert.equal(r.status,502);assert.equal((await r.json()).error,'upstream_http_302');assert.equal(calls,1);assert.equal(puts,0);});
