const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../mission-draft-core.js');
function fixture(){const values=new Map([['ga_active_mission',JSON.stringify({missionId:'old'})],['ga_active_passenger','old-pax']]);const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};const session=create({storage,key:'draft',vault:{save(){throw Error('no vault');}}});return{session,storage,values};}
const draft={currentMissionData:{missionId:'new',sceneAccepted:true},activePassenger:{name:'Elena'}};
function adapters(events,overrides={}){return{readRemote:async()=>{events.push('read');return{revision:7,logbook:['old']};},cleanup:async()=>events.push('cleanup'),publish:async(s,b)=>{events.push('publish');assert.equal(s.currentMissionData.missionId,'new');assert.equal(b.revision,7);return{revision:8};},install:async()=>events.push('install'),...overrides};}
test('preview persists separately and rejects old delayed saves',async()=>{const f=fixture();f.session.begin({previousMissionId:'old'});assert.equal(f.session.save({currentMissionData:{missionId:'old'}}),false);assert.equal(await f.session.read(),null);f.session.save(draft);assert.equal(JSON.parse(f.storage.getItem('ga_active_mission')).missionId,'old');assert.equal(f.storage.getItem('ga_active_passenger'),'old-pax');assert.equal((await f.session.read()).currentMissionData.missionId,'new');});
test('reload preserves a local draft without replaying acceptance',async()=>{const f=fixture();f.session.begin();f.session.save(draft);f.session.phase('committing');const loaded=create({storage:f.storage,key:'draft'});assert.equal(loaded.status(),'review');assert.deepEqual(await loaded.read(),draft);});
test('discard never deletes accepted mission or passenger',()=>{const f=fixture();f.session.begin();f.session.save(draft);f.session.discard();assert.equal(f.session.active(),false);assert.ok(f.storage.getItem('ga_active_mission'));assert.equal(f.storage.getItem('ga_active_passenger'),'old-pax');});
test('accept reads before cleanup then publishes before installing',async()=>{const f=fixture(),events=[];f.session.begin();f.session.save(draft);assert.equal((await f.session.commit(adapters(events))).ok,true);assert.deepEqual(events,['read','cleanup','publish','install']);assert.equal(f.session.active(),false);});
for(const stage of ['readRemote','cleanup','publish','install'])test(stage+' failure retains the complete draft and stops downstream work',async()=>{const f=fixture(),events=[];f.session.begin();f.session.save(draft);const result=await f.session.commit(adapters(events,{[stage]:async()=>{throw Error(stage);}}));assert.equal(result.ok,false);assert.equal(result.error,stage);assert.deepEqual(await f.session.read(),draft);assert.equal(f.session.status(),'review');const downstream={readRemote:['cleanup','publish','install'],cleanup:['publish','install'],publish:['install'],install:[]}[stage];for(const next of downstream)assert.ok(!events.includes(next));});
test('double accept deduplicates the full operation',async()=>{const f=fixture(),events=[];f.session.begin();f.session.save(draft);let release;const a=adapters(events,{readRemote:()=>new Promise(r=>release=r)});const first=f.session.commit(a),second=f.session.commit(a);assert.equal(first,second);assert.equal(f.session.discard(),false);await new Promise(r=>setImmediate(r));release({revision:7});assert.equal((await first).ok,true);assert.deepEqual(events,['cleanup','publish','install']);});
test('pilot changed during remote read prevents cleanup',async()=>{const f=fixture(),events=[];f.session.begin();f.session.save(draft);let current=true;const a=adapters(events,{readRemote:async()=>{current=false;return{};},isCurrent:()=>current});assert.equal((await f.session.commit(a)).ok,false);assert.deepEqual(events,[]);assert.deepEqual(await f.session.read(),draft);});
test('clear can use the exclusive lifecycle without overwriting an existing draft',async()=>{const f=fixture();f.session.begin();f.session.save(draft);const result=await f.session.commit({requiresDraft:false,readRemote:async()=>{throw Error('offline');}});assert.equal(result.ok,false);assert.deepEqual(await f.session.read(),draft);});
test('empty clear does not require a generated mission',async()=>{const f=fixture(),events=[];f.session.begin();assert.equal((await f.session.commit({requiresDraft:false,...adapters(events,{publish:async state=>{assert.equal(state,null);events.push('clear');}})})).ok,true);assert.deepEqual(events,['read','cleanup','clear','install']);});
test('quota fallback resolves complete draft before committing and leaves accepted backups alone',async()=>{const values=new Map(),backups=new Map();let seq=0;const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>{if(JSON.parse(v).state)throw Error('quota');values.set(k,v);},removeItem:k=>values.delete(k)};const vault={save:state=>{const token='draft-'+(++seq);backups.set(token,state);return{token,ready:Promise.resolve()};},load:async token=>backups.get(token)};const f=create({storage,key:'draft',vault});f.begin();f.save(draft);const loaded=create({storage,key:'draft',vault}),events=[];assert.equal((await loaded.commit(adapters(events))).ok,true);assert.deepEqual(events,['read','cleanup','publish','install']);});
test('failed draft persistence does not reach cloud or cleanup',async()=>{const f=fixture(),events=[];f.session.begin();f.storage.setItem=()=>{throw Error('quota');};assert.throws(()=>f.session.save(draft),/no vault/);const result=await f.session.commit(adapters(events));assert.equal(result.ok,false);assert.deepEqual(events,[]);assert.ok(f.values.get('ga_active_mission'));});
