import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import core from '../mission-knowledge-briefing-core.js';
import shared from '../mission-poi-briefing-shared-core.js';
import charter from '../mission-charter-ideas-core.js';
import {extractOriginalFunction} from './extract-original-function.mjs';
const app=fs.readFileSync('app.js','utf8');
const facts=Array.from({length:14},(_,i)=>({text:'Belegter Zielfakt Nummer '+i,topic:i%2?'history':'function',source:'extract'}));
const source={ok:true,status:'accept',exactTitle:true,title:'Arbeitsziel',sourceUrl:'https://de.wikipedia.org/wiki/Arbeitsziel',distanceKm:0.1,facts:facts.slice(0,8),extraFacts:facts.slice(8)};
const c={id:'poi:48:8',target:{name:'Arbeitsziel',lat:48,lon:8},profileId:'tour_guide_knowledge',knowledgeContext:source,knowledgeFacts:facts.map((f,i)=>({id:'knowledge-'+i,fact:f.text,source:source.sourceUrl})),facts:[],targetFacts:[],coverage:[],supplements:[],terrain:{status:'missing'}};
const idea={targetId:c.id,targetName:c.target.name,profileId:c.profileId,focus:'Die heutige Funktion verstehen',situation:'Ein Freund möchte den Ort zeigen.',factIds:['knowledge-1'],person:{name:'Kim',role:'Technikinteressiert',gender:'female'}};
const raw={targetId:c.id,title:'Ein interessanter Blick',story:'Du fliegst mit Kim zum Ziel. Sie möchte dir seine Funktion näherbringen.',greetingSpeaker:'Kim',greeting:'Ich freue mich, dir das zu zeigen.',memory:'Funktion gemeinsam kennenlernen.',usedFactIds:['knowledge-1'],report:{orientationIds:[]}};
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
function fixture(ctx=c,i=idea){return core.mission(core.validateIdea(i,ctx),core.validateWriter(raw,i,ctx),ctx,{});}
test('source identity and coordinate limits apply before ideas; fourteen facts survive',()=>{assert.equal(core.evidence(source,c.target).extraFacts.length,6);assert.equal(core.evidence({...source,title:'Andere Stadt'},c.target),null);assert.equal(core.evidence({...source,distanceKm:20},c.target),null);assert.equal(core.evidence({...source,sourceUrl:null},c.target),null);});
test('profiles have distinct roles and POI interests without fixed scenario examples',()=>{assert.match(core.profiles.tour_guide_knowledge.perspective,/Freund/);assert.match(core.profiles.historian_guided_tour.perspective,/historische Bedeutung/);assert.equal(core.historicalTarget({tags:{historic:'archaeological_site'}}),true);assert.equal(core.historicalTarget({tags:{man_made:'tower'}}),false);assert.equal(core.bucket({category:'rail'},'generic'),'industry');assert.equal(core.bucket({category:'bridge'},'bridge'),'bridge');const prompt=core.ideaPrompt([core.frame(c)]);assert.doesNotMatch(prompt,/Fernsehturm|Rangierbahnhof|Freiburg/);});
test('unknown fact IDs fail structurally; generated history does not become mandatory content',()=>{assert.throws(()=>core.validateIdea({...idea,factIds:['imagined']},c));assert.throws(()=>core.validateWriter({...raw,usedFactIds:['imagined']},idea,c));const st=storage(),m=fixture();for(let i=0;i<20;i++)core.remember(st,'m'+i,m.knowledgeBriefing);assert.equal(core.history(st).length,12);assert.equal(core.history(st)[0].focus,idea.focus);});
test('real profile application preserves writer prose and original learning task parameters',()=>{const env={window:{MissionKnowledgeBriefingCore:core},getMissionTaskProfile:id=>({id})};vm.createContext(env);vm.runInContext(extractOriginalFunction(app,'applyMissionTaskProfileToMission'),env);const m=fixture();const result=env.applyMissionTaskProfileToMission(m,true,'tour_guide_knowledge',m.pax,m.cargo);assert.equal(result.mission.s,m.s);assert.equal(m.passenger.relationshipToPilot,'Freund');assert.equal(m.passenger.targetDwellMin,4);assert.equal(m.passenger.targetRadiusNm,3);});
test('compact local serializer and serialized voice carry full facts and shared memory',()=>{const env={};vm.createContext(env);vm.runInContext(extractOriginalFunction(app,'compactMissionObjectForQuotaStorage'),env);const m=fixture();const compact=JSON.parse(JSON.stringify(env.compactMissionObjectForQuotaStorage(m)));assert.equal(compact.knowledgeBriefing.knowledgeFacts.length,14);assert.equal(compact.knowledgeContext.extraFacts.length,6);const voice=core.voiceContext(compact.knowledgeBriefing);assert.match(voice,/Freund/);assert.match(voice,/Belegter Zielfakt Nummer 13/);});
test('selected browser proposal elaborates once, retaining target, sources and person',async()=>{let calls=0;const env={window:{MissionKnowledgeBriefingCore:core,MissionPoiBriefingSharedCore:shared,MissionCharterIdeasCore:charter},localStorage:storage(),getMissionAircraftCapabilitySnapshot:()=>({passengerCapacity:1}),getSelectedAiApiKey:()=>'',fetchGeminiJsonWithFallback:async()=>{calls++;return {parsed:raw};}};vm.runInNewContext(fs.readFileSync('mission-knowledge-briefing-browser.js','utf8'),env);const start={name:'Start',lat:47,lon:8};const proposal={schema:'knowledge-proposal.v1',start,context:c,idea};const m=await env.window.MissionKnowledgeBriefingBrowser.story({start,dest:c.target,profileId:c.profileId,proposal});assert.equal(calls,1);assert.equal(m.passenger.name,'Kim');assert.equal(m.knowledgeBriefing.knowledgeFacts.length,14);assert.equal(m.knowledgeContext.sourceUrl,source.sourceUrl);assert.equal(env.window.MissionKnowledgeBriefingBrowser.enabled({profileId:'science_geo'}),false);});
test('picker retains a sourced candidate when another candidate has no matching source',async()=>{const good={...c.target,knowledgeContext:source},bad={name:'Ohne Quelle',lat:49,lon:8};const env={window:{MissionKnowledgeBriefingCore:core,MissionPoiBriefingSharedCore:shared,MissionPoiBriefingSharedBrowser:{context:async dest=>({...c,target:dest}),enrichSelected:async x=>x}},localStorage:storage(),getMissionAircraftCapabilitySnapshot:()=>({passengerCapacity:1}),getSelectedAiApiKey:()=>'',fetchGeminiJsonWithFallback:async()=>({parsed:{ideas:[idea]}}),normalizeMissionProposalChoice:x=>x,missionProposalCompactTarget:x=>x,missionProposalFormatRoute:()=>({label:'Route'})};vm.runInNewContext(fs.readFileSync('mission-knowledge-briefing-browser.js','utf8'),env);const rows=await env.window.MissionKnowledgeBriefingBrowser.choices([bad,good],{profileId:c.profileId,start:{name:'Start',lat:47,lon:8}});assert.equal(rows.length,1);assert.equal(rows[0].target.name,good.name);assert.equal(rows[0].knowledgeProposal.context.knowledgeFacts.length,14);});

test('prompts state fact cap and preflight perspective before generation',()=>{assert.match(core.ideaPrompt([core.frame(c)]),/höchstens acht/);const prompt=core.writerPrompt(c,idea,[],shared.prepareFlight({}));assert.match(prompt,/vor dem Start gelesen/);assert.match(prompt,/beim Boarding vor dem Start/);assert.match(prompt,/neugierigen Laien/);});
