const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const training=require('../mission-training-core.js').create({}, {now:()=>1});
const source=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8');
function extract(name,c){const start=source.search(new RegExp('(?:async )?function '+name+'\\('));const tail=source.slice(start);const end=tail.slice(1).search(/\n(?:async )?function /);vm.runInContext(end<0?tail:tail.slice(0,end+1),c);}
function context(){let rotations=0;const c=vm.createContext({window:{missionTrainingProcedure:training},currentStartICAO:'START',TRAINING_CARGO_ITEMS:['Unterlagen'],Math,_missionPipelineV4PolishGermanVisibleText:s=>s,buildInstructorPassenger:plan=>{rotations++;return {name:'Testinstruktorin',gender:'female',role:'Fluglehrerin',trainingPlan:plan||{focus:['A','B'],requiredCount:2}};}});for(const n of ['trainingNarrativeHistory','rememberTrainingNarrative','prepareExecutableTraining','enforceAptTrainingMission','enforceTrainingContractFields','enforceTrainingPlannerResultFields'])extract(n,c);c.rotations=()=>rotations;return c;}
test('accepted narrative retains instructor, exact plan, baggage and prose without reroll',()=>{const c=context(),plan={focus:['A','B','C'],requiredCount:2},passenger={name:'Lea',gender:'female',trainingPlan:plan};const m={t:'Eigener Titel',s:'Eigener Text',passenger,cargoText:'Eigene Tasche',_trainingNarrative:{schema:'training-narrative.v1'}};const out=c.enforceAptTrainingMission(m,'Ziel').mission;assert.equal(out.passenger,passenger);assert.equal(out.passenger.trainingPlan,plan);assert.equal(out.s,m.s);assert.equal(out.t,m.t);assert.equal(out.cargoText,m.cargoText);assert.equal(c.rotations(),0);});
test('local fallback names only executable exercises with correct instructor gender',()=>{const c=context(),m=c.enforceAptTrainingMission({passenger:{trainingPlan:{focus:['No-Flaps-Approach','Touch-and-Go'],requiredCount:2}}},'Ziel').mission;assert.match(m.s,/Sie hat 2 Übungen vorbereitet/);assert.doesNotMatch(m.s,/Er hat|No-Flaps|Touch-and-Go/);assert.deepEqual(Array.from(m.passenger.trainingPlan.focus),Array.from(m.passenger.trainingRecipe.exercises,e=>e.label));});
test('training frame replaces inherited charter motivation',()=>{const c=context(),dirty={profile:{},target:{},storyFrame:{whyNow:'Termindruck'},missionPlan:{plan:{mustMention:['30 lbs','Termindruck'],realism:'Charter',storyFrame:{whyNow:'Termin'}}}};const fixed=c.enforceTrainingContractFields(dirty);assert.doesNotMatch(JSON.stringify(fixed),/Termindruck|Charter|30 lbs/);const planned=c.enforceTrainingPlannerResultFields({plan:dirty.missionPlan.plan});assert.doesNotMatch(JSON.stringify(planned),/Termindruck|Charter|30 lbs/);assert.equal(dirty.storyFrame.whyNow,'Termindruck');});
test('training writer keeps accepted prose and passes fixed exercises before generation',async()=>{const c=context();let prompt='';c.window.MissionPrivateEpisodeV6={flightContext:()=>({weather:[]}),flightBindings:()=>({}),resolveFlightBriefing:()=>null,weatherFallback:()=> 'Wetter nicht verfügbar.'};c.window.MissionCargoIdeasCore={weatherPrompt:()=>''};c.getSelectedAiApiKey=()=> 'fixture';c.fetchGeminiJsonWithFallback=async p=>{prompt=p;return {source:'Gemini',parsed:{title:'Trainingsflug',story:'Ein frei geschriebener Vorflugtext über die geplante Zusammenarbeit und die vorbereiteten Übungen. '.repeat(3),greeting:'Hallo, wir gehen das heute in Ruhe gemeinsam an.',flightBriefing:''}};};extract('fetchTrainingNarrative',c);const m=await c.fetchTrainingNarrative({missionContractV4:{profile:{},target:{name:'Ziel'},route:{}},passenger:{trainingPlan:{focus:['A','B'],requiredCount:2}}});assert.match(prompt,/Testinstruktorin/);assert.match(prompt,/requiredExercises/);assert.doesNotMatch(prompt,/\"instructorLine\"/);assert.match(m.s,/frei geschriebener/);assert.match(m.s,/Wetter nicht verfügbar/);assert.equal(c.enforceAptTrainingMission(m,'Ziel').mission.s,m.s);assert.equal(m._missionContractV4.passenger,m.passenger);});

test('explicit recipe survives JSON transport and both runtime normalizers without reordering',()=>{const c=context();for(const isPOI of [false,true]){const m=c.enforceAptTrainingMission({},'Ziel',{isPOI}).mission;const restored=JSON.parse(JSON.stringify(m));const actual=training.normalizeRecipe(null,restored,restored.passenger);assert.deepEqual(actual.exercises,JSON.parse(JSON.stringify(m.passenger.trainingRecipe.exercises)));assert.equal(actual.requiredCount,m.passenger.trainingPlan.requiredCount);assert.equal(actual.mode,'airwork');const before=actual.exercises.map(e=>e.id);c.prepareExecutableTraining(restored.passenger,'Ziel');assert.deepEqual(Array.from(restored.passenger.trainingRecipe.exercises,e=>e.id),before);}});

test('history contains only bounded generated texts and tolerates corrupt storage',()=>{const c=context(),data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};for(let i=0;i<12;i++)c.rememberTrainingNarrative(storage,{t:'Titel '+i,_missionWriterV4Debug:{rawAiStory:'Text '+i},passenger:{greetingText:'Hallo',trainingRecipe:{exercises:[{label:'Vollkreis'}]}}},i%2===0);const rows=c.trainingNarrativeHistory(storage);assert.equal(rows.length,8);assert.equal(rows[0].title,'Titel 4');assert.equal(rows.at(-1).story,'Text 11');storage.setItem('ga_training_narrative_history_v1','broken');assert.equal(c.trainingNarrativeHistory(storage).length,0);});

test('subsequent writer sees its own prior generated title and text, not weather or fixed scenarios',async()=>{const c=context(),data=new Map();c.localStorage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};c.window.MissionPrivateEpisodeV6={flightContext:()=>({weather:[]}),flightBindings:()=>({}),resolveFlightBriefing:()=>null,weatherFallback:()=> 'WEATHER_SENTINEL'};c.window.MissionCargoIdeasCore={weatherPrompt:()=>''};c.getSelectedAiApiKey=()=> 'fixture';const prompts=[];c.fetchGeminiJsonWithFallback=async p=>{prompts.push(p);return {parsed:{title:'OWN_TITLE_'+prompts.length,story:'Eine eigenständige geplante Trainingsgeschichte mit klarem Übungsschwerpunkt und kontrollierten Manövern. '.repeat(3),greeting:'Hallo, wir gehen die Übungen gemeinsam durch.',flightBriefing:''}};};extract('fetchTrainingNarrative',c);const ctx={missionContractV4:{profile:{},target:{name:'Ziel'},route:{}}};await c.fetchTrainingNarrative(ctx);await c.fetchTrainingNarrative(ctx);assert.doesNotMatch(prompts[0],/OWN_TITLE_1/);assert.match(prompts[1],/OWN_TITLE_1/);assert.doesNotMatch(prompts[1],/WEATHER_SENTINEL/);assert.equal(c.trainingNarrativeHistory(c.localStorage).length,2);});
