import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import core from '../mission-chain-briefing-core.js';
import shared from '../mission-poi-briefing-shared-core.js';
import narrative from '../mission-poi-followup-narrative-core.js';
import voice from '../mission-poi-voice-core.js';
import trackerVoice from '../ga-tracker-client/tracker-mission-poi-chain-voice.js';
import {extractOriginalFunction} from './extract-original-function.mjs';
const app=fs.readFileSync('app.js','utf8');
const chain={key:'test-chain',label:'Linie',theme:'road',points:[{id:'p1',name:'Querung',lat:48,lon:8},{id:'p2',name:'Brücke',lat:48.1,lon:8.1}],hiddenOutcome:{pointId:'p2',findingHint:'Verborgener Schaden',followUpProfileId:'inspection_infra'}};
const c={id:'chain-id',target:{name:'Linie',lat:48,lon:8},chainPlan:core.plan(chain),facts:[],targetFacts:[],coverage:[],supplements:[],terrain:{status:'missing'}};
const idea={targetId:c.id,targetName:'Linie',client:{name:'Betreiber',kind:'operator'},commission:'Eine gemeinsame Planung vorbereiten.',purpose:'Welche Bereiche brauchen eine Nachprüfung?',person:{name:'Mia',role:'Prüferin',gender:'female'},pointFocus:[{pointId:'p1',question:'Gesamtform vergleichen.'},{pointId:'p2',question:'Die Übergänge einordnen.'}]};
const raw={targetId:c.id,title:'Gemeinsamer Erstbefund',story:'Du fliegst mit Mia zur Linie für einen zusammenhängenden Erstbefund.',greetingSpeaker:'Mia',greeting:'Danke fürs Mitnehmen.',memory:'Gemeinsame Planung und offene Nachprüfungsfrage.',usedFactIds:[],voices:{entry:'Wir vergleichen die Abschnitte für die Planung.',points:[{pointId:'p1',text:'Den Abschnitt können wir später im Zusammenhang vergleichen.'},{pointId:'p2',text:'Der Vergleich hilft bei der Planung weiterer Prüfungen.'}],complete:'An der Basis übergeben wir die Aufnahmen an den Betreiber.'},report:{orientationIds:[]}};
function fixture(){return core.mission(core.validateIdea(idea,c),core.validateWriter(raw,idea,c),c,chain,{});}
const prepare=(ctx,events)=>trackerVoice.prepareEvents(ctx,events,ctx.chainSpec,1000);
function context(b=null){return {schema:voice.CONTEXT_SCHEMA,version:1,missionId:'test-chain',taskDomain:'infra_chain_recon',strict:true,baseContext:'Kettenauftrag',passenger:{name:'Mia'},speaker:{name:'Mia'},audioEnabled:true,chainSpec:chain,chainBriefing:b,chainAudioDefinitions:{photo:{gain:.78},handoff:{gain:.54},scan_start:{gain:.58}}};}
test('public chain frame excludes hidden findings and preserves existing point identities',()=>{assert.doesNotMatch(core.ideaPrompt([core.frame(c)]),/Verborgener Schaden|followUpProfileId/);assert.deepEqual(core.plan(chain).points.map(p=>p.id),['p1','p2']);assert.throws(()=>core.plan({...chain,points:[chain.points[0],chain.points[0]]}));assert.throws(()=>core.validateIdea({...idea,pointFocus:[idea.pointFocus[0],idea.pointFocus[0]]},c));assert.throws(()=>core.validateWriter({...raw,voices:{...raw.voices,points:[{pointId:'p3',text:'Falsch'}]}},idea,c));});
test('mission retains exact execution chain and writer prose in real profile application',()=>{const m=fixture();assert.equal(m.poiChain,chain);assert.deepEqual(m.poiChain.hiddenOutcome,chain.hiddenOutcome);const env={window:{MissionChainBriefingCore:core},getMissionTaskProfile:id=>({id})};vm.createContext(env);vm.runInContext(extractOriginalFunction(app,'applyMissionTaskProfileToMission'),env);assert.equal(env.applyMissionTaskProfileToMission(m,true,'infra_chain_recon',m.pax,m.cargo).mission.s,m.s);});
test('serialized chain voice appends story without replacing released finding or cue timing',()=>{const b=JSON.parse(JSON.stringify(fixture().chainBriefing));const events=[{type:'point_complete',point:chain.points[1],hiddenOutcome:{paxFindingText:'Die freigegebene Auffälligkeit ist sichtbar.'}},{type:'chain_complete'}];const old=prepare(context(),events),updated=prepare(context(b),events);assert.equal(updated.length,old.length);for(let i=0;i<old.length;i++)assert.deepEqual(updated[i].resolvedRecipe.cueSequence,old[i].resolvedRecipe.cueSequence);assert.match(updated[0].resolvedRecipe.fallbackText,/freigegebene Auffälligkeit/);assert.match(updated[0].resolvedRecipe.fallbackText,/Vergleich hilft/);assert.match(updated[1].resolvedRecipe.fallbackText,/übergeben/);});
test('silent events and corrections stay unchanged; mismatched plans cannot narrate another chain',()=>{const b=fixture().chainBriefing;for(const type of ['corridor_segment_complete','corridor_segment_reset_offtrack','corridor_segment_reset_speed','chain_corridor_complete'])assert.deepEqual(prepare(context(b),[{type,point:chain.points[0]}]),prepare(context(),[{type,point:chain.points[0]}]));const wrong=structuredClone(b);wrong.plan.points[0].id='other';assert.deepEqual(prepare(context(wrong),[{type:'chain_complete'}]),prepare(context(),[{type:'chain_complete'}]));});
test('compact mission retains chain story and completion hands the actual finding to the existing follow-up',()=>{const env={window:{missionPoiChain:{compactPoiChain:x=>x}}};vm.createContext(env);vm.runInContext(extractOriginalFunction(app,'compactMissionObjectForQuotaStorage'),env);const m={...fixture(),missionId:'m1'};const compact=JSON.parse(JSON.stringify(env.compactMissionObjectForQuotaStorage(m)));assert.equal(compact.chainBriefing.voices.points.length,2);const handoff=narrative.complete(compact,{poiFollowUp:true,followUpProfileId:'inspection_infra',followUpLabel:'Gezielte Nachprüfung'}, {missionId:'m1',result:'completed',completionId:'done'});assert.equal(handoff.memory.client.name,'Betreiber');assert.equal(handoff.memory.participants[0].name,'Mia');assert.equal(handoff.nextAssignment.profileId,'inspection_infra');assert.equal(narrative.complete(compact,{}, {missionId:'m1',result:'failed',failed:true}),null);});

test('browser binds one idea and writer to original chain without leaking finding to prompts',async()=>{const calls=[];const env={window:{MissionChainBriefingCore:core,MissionPoiBriefingSharedCore:shared,MissionPoiBriefingSharedBrowser:{context:async()=>c},MissionCharterIdeasCore:{resolveReferences:x=>x}},localStorage:{getItem:()=>null},getMissionAircraftCapabilitySnapshot:()=>({passengerCapacity:1}),getSelectedAiApiKey:()=>'',fetchGeminiJsonWithFallback:async prompt=>{calls.push(prompt);return {parsed:calls.length===1?{ideas:[idea]}:raw};}};vm.runInNewContext(fs.readFileSync('mission-chain-briefing-browser.js','utf8'),env);const m=await env.window.MissionChainBriefingBrowser.story({start:{name:'Start',lat:47,lon:8},dest:{...c.target,poiChain:chain}});assert.equal(calls.length,2);assert.equal(m.poiChain,chain);assert.equal(m.followUpNarrative.memory.client.name,'Betreiber');assert.doesNotMatch(calls.join(' '),/Verborgener Schaden/);assert.equal(env.window.MissionChainBriefingBrowser.enabled({profileId:'inspection_infra'}),false);});
test('corridor entry narrates once while point-only chains use their area entry',()=>{const b=fixture().chainBriefing;const corridor={...context(b),chainSpec:{...chain,corridor:{required:true}}};const area=prepare(corridor,[{type:'chain_area_entered'}]);assert.doesNotMatch(area[0].resolvedRecipe.fallbackText,/Wir vergleichen die Abschnitte/);const entered=prepare(corridor,[{type:'chain_corridor_entered'}]);assert.match(entered[0].resolvedRecipe.fallbackText,/Wir vergleichen die Abschnitte/);assert.match(prepare(context(b),[{type:'chain_area_entered'}])[0].resolvedRecipe.fallbackText,/Wir vergleichen die Abschnitte/);});

test('speaker identity comes from assigned passenger, optional academic title does not reject prose',()=>{const titled={...idea,person:{...idea.person,name:'Dipl.-Geogr. Mia Beispiel'}};const written=core.validateWriter({...raw,greetingSpeaker:'Mia Beispiel'},titled,c);assert.equal(written.greetingSpeaker,titled.person.name);assert.equal(written.story,raw.story);assert.deepEqual(written.voices,raw.voices);});
