const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const training=require('../mission-training-core.js').create({}, {now:()=>1});
const source=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8');
function extract(name,c){const start=source.search(new RegExp('(?:async )?function '+name+'\\('));const tail=source.slice(start);const end=tail.slice(1).search(/\n(?:async )?function /);vm.runInContext(end<0?tail:tail.slice(0,end+1),c);}
function context(){let rotations=0;const c=vm.createContext({window:{missionTrainingProcedure:training},currentStartICAO:'START',TRAINING_CARGO_ITEMS:['Unterlagen'],Math,_missionPipelineV4PolishGermanVisibleText:s=>s,buildInstructorPassenger:plan=>{rotations++;return {name:'Testinstruktorin',gender:'female',role:'Fluglehrerin',trainingPlan:plan||{focus:['A','B'],requiredCount:2}};}});for(const n of ['fetchTrainingCoaching','trainingNarrativeIssues','trainingBriefingKnowledge','trainingNarrativeHistory','rememberTrainingNarrative','prepareExecutableTraining','enforceAptTrainingMission','enforceTrainingContractFields','enforceTrainingPlannerResultFields'])extract(n,c);c.rotations=()=>rotations;return c;}
function fixtureAnswer(prompt,title='Trainingsflug') {
 if(prompt.includes('CONTEXT: ')) {
  const ctx=JSON.parse(prompt.split('CONTEXT: ')[1].split(' KORREKTURBEDARF: ')[0]);
  return {briefingTip:{exerciseId:ctx.requiredExerciseIds[0],text:'Ein fachlicher Hinweis zum kontrollierten Ausführen der vorbereiteten Übung.'},practiceFactIds:['radio_readback'],practiceTips:[{factId:'radio_readback',text:'ATC-Höhenanweisungen und QNH werden zurückgelesen; Flugplatzinformation ist keine ATC-Freigabe.'}],maneuverTips:ctx.allExerciseIds.map(id=>({exerciseId:id,text:'Ein ergänzender fliegerischer Hinweis zum kontrollierten Manöver.'}))};
 }
 return {title,story:'Ein frei geschriebener Vorflugtext über die geplante Zusammenarbeit und die vorbereiteten Übungen. '.repeat(3),greeting:'Hallo, wir gehen das heute in Ruhe gemeinsam an.',flightBriefing:''};
}
test('accepted narrative retains instructor, exact plan, baggage and prose without reroll',()=>{const c=context(),plan={focus:['A','B','C'],requiredCount:2},passenger={name:'Lea',gender:'female',trainingPlan:plan};const m={t:'Eigener Titel',s:'Eigener Text',passenger,cargoText:'Eigene Tasche',_trainingNarrative:{schema:'training-narrative.v1'}};const out=c.enforceAptTrainingMission(m,'Ziel').mission;assert.equal(out.passenger,passenger);assert.equal(out.passenger.trainingPlan,plan);assert.equal(out.s,m.s);assert.equal(out.t,m.t);assert.equal(out.cargoText,m.cargoText);assert.equal(c.rotations(),0);});
test('local fallback names only executable exercises with correct instructor gender',()=>{const c=context(),m=c.enforceAptTrainingMission({passenger:{trainingPlan:{focus:['No-Flaps-Approach','Touch-and-Go'],requiredCount:2}}},'Ziel').mission;assert.match(m.s,/Sie hat 2 Übungen vorbereitet/);assert.doesNotMatch(m.s,/Er hat|No-Flaps|Touch-and-Go/);assert.deepEqual(Array.from(m.passenger.trainingPlan.focus),Array.from(m.passenger.trainingRecipe.exercises,e=>e.label));});
test('training frame replaces inherited charter motivation',()=>{const c=context(),dirty={profile:{},target:{},storyFrame:{whyNow:'Termindruck'},missionPlan:{plan:{mustMention:['30 lbs','Termindruck'],realism:'Charter',storyFrame:{whyNow:'Termin'}}}};const fixed=c.enforceTrainingContractFields(dirty);assert.doesNotMatch(JSON.stringify(fixed),/Termindruck|Charter|30 lbs/);const planned=c.enforceTrainingPlannerResultFields({plan:dirty.missionPlan.plan});assert.doesNotMatch(JSON.stringify(planned),/Termindruck|Charter|30 lbs/);assert.equal(dirty.storyFrame.whyNow,'Termindruck');});
test('training writer keeps accepted prose and passes fixed exercises before generation',async()=>{const c=context();let prompt='';c.window.MissionPrivateEpisodeV6={flightContext:()=>({weather:[]}),flightBindings:()=>({}),resolveFlightBriefing:()=>null,weatherFallback:()=> 'Wetter nicht verfügbar.'};c.window.MissionCargoIdeasCore={weatherPrompt:()=>''};c.getSelectedAiApiKey=()=> 'fixture';const prompts=[];c.fetchGeminiJsonWithFallback=async p=>{prompts.push(p);prompt=p;return {source:'Gemini',parsed:fixtureAnswer(p)};};extract('fetchTrainingNarrative',c);const m=await c.fetchTrainingNarrative({missionContractV4:{profile:{},target:{name:'Ziel'},route:{}},passenger:{trainingPlan:{focus:['A','B'],requiredCount:2}}});assert.match(prompt,/Testinstruktorin/);assert.equal(prompts.length,2);assert.match(prompts[0],/requiredExercises/);assert.match(prompts[0],/crewResponsibilities/);assert.match(prompts[0],/von ihm stabilisierten Fluglage/);assert.match(prompts[0],/Ich-\/Wir-Form/);assert.doesNotMatch(prompts[0],/knowledge|practiceFactIds|maneuverTips/);assert.match(prompts[1],/allExerciseIds/);assert.match(prompts[1],/knowledge/);assert.doesNotMatch(prompt,/\"instructorLine\"/);assert.match(m.s,/frei geschriebener/);assert.match(m.s,/Wetter nicht verfügbar/);assert.equal(c.enforceAptTrainingMission(m,'Ziel').mission.s,m.s);assert.equal(m._missionContractV4.passenger,m.passenger);assert.ok(m.passenger.trainingRecipe.exercises.every(e=>e.inflightTip));assert.ok(training.normalizeRecipe(null,JSON.parse(JSON.stringify(m)),m.passenger).exercises.every(e=>e.inflightTip));});

test('explicit recipe survives JSON transport and both runtime normalizers without reordering',()=>{const c=context();for(const isPOI of [false,true]){const m=c.enforceAptTrainingMission({},'Ziel',{isPOI}).mission;const restored=JSON.parse(JSON.stringify(m));const actual=training.normalizeRecipe(null,restored,restored.passenger);assert.deepEqual(actual.exercises,JSON.parse(JSON.stringify(m.passenger.trainingRecipe.exercises)));assert.equal(actual.requiredCount,m.passenger.trainingPlan.requiredCount);assert.equal(actual.mode,'airwork');const before=actual.exercises.map(e=>e.id);c.prepareExecutableTraining(restored.passenger,'Ziel');assert.deepEqual(Array.from(restored.passenger.trainingRecipe.exercises,e=>e.id),before);}});

test('history contains only bounded generated texts and tolerates corrupt storage',()=>{const c=context(),data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};for(let i=0;i<12;i++)c.rememberTrainingNarrative(storage,{t:'Titel '+i,_missionWriterV4Debug:{rawAiStory:'Text '+i},passenger:{greetingText:'Hallo',trainingRecipe:{exercises:[{label:'Vollkreis'}]}}},i%2===0);const rows=c.trainingNarrativeHistory(storage);assert.equal(rows.length,8);assert.equal(rows[0].title,'Titel 4');assert.equal(rows.at(-1).story,'Text 11');storage.setItem('ga_training_narrative_history_v1','broken');assert.equal(c.trainingNarrativeHistory(storage).length,0);});

test('subsequent writer sees its own prior generated title and text, not weather or fixed scenarios',async()=>{const c=context(),data=new Map();c.localStorage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};c.window.MissionPrivateEpisodeV6={flightContext:()=>({weather:[]}),flightBindings:()=>({}),resolveFlightBriefing:()=>null,weatherFallback:()=> 'WEATHER_SENTINEL'};c.window.MissionCargoIdeasCore={weatherPrompt:()=>''};c.getSelectedAiApiKey=()=> 'fixture';const prompts=[];c.fetchGeminiJsonWithFallback=async p=>{prompts.push(p);return {parsed:fixtureAnswer(p,'OWN_TITLE_'+prompts.length)};};extract('fetchTrainingNarrative',c);const ctx={missionContractV4:{profile:{},target:{name:'Ziel'},route:{}}};await c.fetchTrainingNarrative(ctx);await c.fetchTrainingNarrative(ctx);assert.doesNotMatch(prompts[0],/OWN_TITLE_1/);assert.match(prompts[2],/OWN_TITLE_1/);assert.doesNotMatch(prompts[2],/WEATHER_SENTINEL/);assert.equal(c.trainingNarrativeHistory(c.localStorage).length,2);});

 test('professional briefing includes scoped source-backed knowledge for actual exercises',()=>{const c=context();const k=c.trainingBriefingKnowledge({exercises:[{type:'turn_180'}]});assert.equal(k.exerciseGuidance.length,1);assert.equal(k.exerciseGuidance[0].type,'turn_180');assert.match(k.exerciseGuidance[0].guidance,/Gegenkurs/);assert.equal(k.practiceFacts.length,4);for(const f of k.practiceFacts){assert.match(f.source,/https:\/\/www.easa.europa.eu/);assert.match(f.section,/SERA/);}assert.match(k.practiceFacts.find(f=>f.id==='cloud_distance').text,/höherer Wert/);assert.match(k.practiceFacts.find(f=>f.id==='minimum_height').text,/600-m-Radius/);assert.match(k.scope,/Außerhalb/);});

test('normalized 30 and 45 degree turns receive distinct guidance',()=>{const c=context(),k=c.trainingBriefingKnowledge({exercises:[{type:'constant_bank_360',targetBankDeg:30},{type:'constant_bank_360',targetBankDeg:45}]});assert.match(k.exerciseGuidance[0].guidance,/Ausgangskurs/);assert.match(k.exerciseGuidance[1].guidance,/45 Grad/);});

test('tip history preserves selected factual topics independently of truncated prose',()=>{const c=context(),data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};c.rememberTrainingNarrative(storage,{t:'Titel',_missionWriterV4Debug:{rawAiStory:'Langtext'},_trainingNarrative:{practiceFactIds:['minimum_height','radio_readback']},passenger:{greetingText:'Hallo',trainingRecipe:{exercises:[]}}},true);assert.deepEqual(Array.from(c.trainingNarrativeHistory(storage)[0].practiceFactIds),['minimum_height','radio_readback']);});

test('format check reports missing optional tips without interpreting technical prose',()=>{const c=context(),frame={requiredExercises:[{id:'turn',targetBankDeg:45}],optionalExercises:[{id:'climb',altitudeStepFt:500}]};const raw={practiceFactIds:['lookout'],practiceTips:[{factId:'lookout',text:'Die fortlaufende Außenbeobachtung bleibt während jeder Übung wichtig.'}],maneuverTips:[{exerciseId:'turn',text:'Mit 45 Grad die Querneigung kontrolliert halten.'}]};assert.match(c.trainingNarrativeIssues(raw,frame).join(' '),/climb/);raw.maneuverTips.push({exerciseId:'climb',text:'Bereits 50 Fuß vor der Zielhöhe abfangen.'});assert.equal(c.trainingNarrativeIssues(raw,frame).length,0);raw.maneuverTips[1].text='Das Abfangen passend zur Steigrate und zur Reaktion des Flugzeugs vorbereiten.';assert.equal(c.trainingNarrativeIssues(raw,frame).length,0);raw.practiceTips=[];assert.match(c.trainingNarrativeIssues(raw,frame).join(' '),/ausformulierten/);});

test('coaching repairs independently without regenerating accepted story',async()=>{const c=context(),calls=[];c.window.MissionPrivateEpisodeV6={flightContext:()=>({weather:[]}),flightBindings:()=>({}),resolveFlightBriefing:()=>null,weatherFallback:()=> 'Wetter unbekannt.'};c.window.MissionCargoIdeasCore={weatherPrompt:()=>''};c.getSelectedAiApiKey=()=> 'fixture';c.fetchGeminiJsonWithFallback=async(p,k,o)=>{calls.push(o.promptVersion);const answer=fixtureAnswer(p);if(calls.length===2)answer.maneuverTips.pop();return {parsed:answer};};extract('fetchTrainingNarrative',c);const m=await c.fetchTrainingNarrative({missionContractV4:{profile:{},target:{name:'Ziel'},route:{}}});assert.deepEqual(calls,['training-narrative-v9','training-coaching-v4','training-coaching-v4']);assert.match(m.s,/frei geschriebener/);assert.match(m.s,/ATC-Höhenanweisungen/);assert.equal(m._trainingNarrative.practiceTips.length,1);});

test('failed coaching does not save a partial mission to history',async()=>{const c=context(),data=new Map();c.localStorage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};c.window.MissionPrivateEpisodeV6={flightContext:()=>({weather:[]}),flightBindings:()=>({})};c.window.MissionCargoIdeasCore={weatherPrompt:()=>''};c.getSelectedAiApiKey=()=> 'fixture';c.fetchGeminiJsonWithFallback=async p=>({parsed:p.includes('CONTEXT: ')?{}:fixtureAnswer(p)});extract('fetchTrainingNarrative',c);await assert.rejects(c.fetchTrainingNarrative({missionContractV4:{profile:{},target:{name:'Ziel'},route:{}}}),/fachlichen Trainingshinweise/);assert.equal(c.trainingNarrativeHistory(c.localStorage).length,0);});

test('stall source includes possible soft controls without universal force prediction',()=>{const c=context(),k=c.trainingBriefingKnowledge({exercises:[{id:'stall',type:'stall_recovery'}]});assert.match(k.exerciseGuidance[0].guidance,/weicher/);assert.match(k.exerciseGuidance[0].guidance,/Trimmung/);assert.match(k.exerciseGuidance[0].additionalSource,/06_afh_ch5/);});

test('maneuver angle is not mistaken for an invented technique value',()=>{const c=context(),frame={requiredExercises:[{id:'turn',type:'turn_180',targetBankDeg:30}],optionalExercises:[]};const raw={practiceFactIds:['lookout'],practiceTips:[{factId:'lookout',text:'Die fortlaufende Außenbeobachtung bleibt während jeder Übung wichtig.'}],maneuverTips:[{exerciseId:'turn',text:'Während der 180-Grad-Wende die Höhe und die Querneigung kontrollieren.'}]};assert.equal(c.trainingNarrativeIssues(raw,frame).length,0);});

test('expanded coaching accepts detailed tips within the transport limit',()=>{const c=context(),frame={requiredExercises:[{id:'turn',type:'constant_bank_360',targetBankDeg:30}],optionalExercises:[]};const text='Außenblick und Instrumentenkontrolle ergänzen sich bei der Beobachtung der Fluglage. '.repeat(6).trim();assert.ok(text.length>350 && text.length<=600);const raw={practiceFactIds:['lookout'],practiceTips:[{factId:'lookout',text:'Die fortlaufende Außenbeobachtung bleibt während jeder Übung wichtig.'}],maneuverTips:[{exerciseId:'turn',text}]};assert.equal(c.trainingNarrativeIssues(raw,frame).length,0);raw.maneuverTips[0].text='x'.repeat(601);assert.match(c.trainingNarrativeIssues(raw,frame).join(' '),/Hinweislänge/);});

test('training foundation explicitly assigns stabilization to the pilot and preserves rule conditions',()=>{const c=context(),k=c.trainingBriefingKnowledge({exercises:[{id:'turn',type:'turn_180'}]});assert.match(k.exerciseGuidance[0].guidance,/Horizontalflug.*keine Landung/);const fact=k.practiceFacts.find(f=>f.id==='minimum_height');assert.equal(fact.essentialPoints.length,4);assert.match(fact.essentialPoints.join(' '),/behördliche Erlaubnis/);assert.match(k.practiceFacts.find(f=>f.id==='lookout').text,/keine ATC-Staffelung/);});
