'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const core=require('../mission-sar-briefing-core.js'),search=require('../mission-sar-search-core.js');
const c={id:'x',target:{name:'Suchraum',lat:48,lon:8},allowedIncidents:['road_vehicle'],targetFacts:[],environmentFacts:[{id:'sar-way/1',fact:'Straße A'}]};
const idea={targetId:'x',targetName:'Suchraum',incident:'road_vehicle',alarm:'Überfälliges Fahrzeug',lastContact:'Telefonat bei Straße A',uncertainty:'Aufenthalt unbekannt',searchFocus:'Fahrzeug suchen',person:{name:'Mia',role:'SAR-Beobachterin',gender:'female'},factIds:['sar-way/1']};
test('technical identities and factual references are validated without rewriting narrative',()=>{assert.deepEqual(core.validateIdea(idea,c),{...idea,person:{...idea.person,personality:'ruhig, klar, aufmerksam'}});assert.throws(()=>core.validateIdea({...idea,factIds:['unbekannt']},c));assert.throws(()=>core.validateIdea({...idea,targetId:'wrong'},c));assert.throws(()=>core.validateIdea({...idea,person:{...idea.person,gender:'weiblich'}},c));assert.match(core.ideaPrompt([c],[]),/MITFLIEGENDEN/);assert.match(core.voiceContext({schema:core.VERSION,idea}),/ausschließlich der Tracker/);});
test('no-contact composer emits no scene; unsuitable incident or road reference cannot silently place props',async()=>{const w={MissionSarBriefingCore:core,MissionSarSceneCore:require('../mission-sar-scene-core.js')};const env={window:w};vm.runInNewContext(fs.readFileSync(require.resolve('../mission-sar-briefing-browser.js'),'utf8'),env);const md={sarBriefing:{schema:core.VERSION,idea},sarScenario:{schema:'sar-search.v2',center:c.target,radiusNm:1.5,minSearchSec:180,maxSearchSec:600,truth:'no_contact',pending:true}};const geo={sarCandidates:[{incident:'road_vehicle'}],roads:[]};const result=await w.MissionSarBriefingBrowser.composeScene({missionData:md,missionContract:{},geometry:geo,compose:()=>{throw Error('No composer for no contact');}});assert.equal(result.targetScene.kind,'none');assert.equal(result.sarScenario.pending,false);assert.equal(search.validate(result.sarScenario),null);md.sarScenario.truth='incident';await assert.rejects(()=>w.MissionSarBriefingBrowser.composeScene({missionData:md,missionContract:{},geometry:geo}),/Straßenbezug/);});

test('accepted composer location, heading and elevation are retained exactly in the App scene command anchor',async()=>{
 const sc=require('../mission-sar-scene-core.js'),point={x:0,y:700},geo={origin:c.target,radiusM:2200,status:'mapped',shapes:[{type:'meadow',closed:true,blocked:false,points:[{x:-2000,y:-2000},{x:2000,y:-2000},{x:2000,y:2000},{x:-2000,y:2000},{x:-2000,y:-2000}]},{type:'road',closed:false,blocked:true,buffer:7,points:[{x:-2000,y:677},{x:2000,y:677}]}],roads:[{id:'way/1',name:'Straße A',widthM:10,points:[{x:-2000,y:677},{x:2000,y:677}]}],sarCandidates:[{...point,incident:'road_vehicle',roadId:'way/1'}]};
 const w={MissionSarBriefingCore:core,MissionSarSceneCore:sc},env={window:w};vm.runInNewContext(fs.readFileSync(require.resolve('../mission-sar-briefing-browser.js'),'utf8'),env);
 const result=await w.MissionSarBriefingBrowser.composeScene({missionData:{sarBriefing:{schema:core.VERSION,idea},sarScenario:{schema:'sar-search.v2',center:c.target,radiusNm:1.5,minSearchSec:180,maxSearchSec:600,truth:'incident',pending:true}},missionContract:{poiScenePlacementVersion:'poi-placement.v3'},geometry:geo,compose:async packet=>{assert.equal(packet.missionContract.poiScenePlacementVersion,undefined);assert.equal(packet.missionData.sarSearchScene.outputContract.primaryFeature,'road_vehicles');return {debug:{aiRaw:{targetScene:{kind:'road_incident',requirements:[{feature:'road_vehicles',count:1,forwardM:point.y,rightM:point.x}]}}}};},terrain:async()=>0});
 assert.equal(result.sarScenario.source.altFt,0);assert.equal(result.sarScenario.source.lon,c.target.lon);assert.equal(result.targetScene.heading,0);
 const {extractOriginalFunction}=await import('./extract-original-function.mjs');const environment=vm.createContext({currentMissionData:{sarScenario:{...result.sarScenario,scenePlan:result.targetScene},poiTerrainFt:1500}});vm.runInContext(extractOriginalFunction(fs.readFileSync(require.resolve('../sync.js'),'utf8'),'_missionTargetScenePoint'),environment);const anchor=environment._missionTargetScenePoint();assert.equal(anchor.altFt,0);assert.equal(anchor.hdg,0);assert.equal(anchor.lat,c.target.lat);
});

test('acceptance persists the private scene in the contract while keeping ordinary scene previews undisclosed',async()=>{
 const {extractOriginalFunction}=await import('./extract-original-function.mjs');
 const scenario={schema:'sar-search.v2',pending:false,truth:'incident',source:{lat:48,lon:8}},scene={kind:'sar_land',requirements:[{feature:'missing_person',forwardM:500,rightM:0}]};
 const md={sarBriefing:{schema:core.VERSION},missionContract:{taskDomain:'search_and_rescue'},isPOI:true};
 const w={MissionSarBriefingCore:{owns:()=>true},activePassenger:{},gaMissionSceneDebugRecordAi:()=>{}};
 const noop=()=>{},env=vm.createContext({window:w,currentMissionData:md,localStorage:{setItem:noop,getItem:()=>null},enrichMissionTruthWithScene:x=>x,buildMissionTruth:()=>({}),sanitizeMissionSceneIntentSpec:x=>x,storeActiveMissionContractSafely:noop,saveMissionState:noop,updateMissionAcceptanceUi:noop,refreshMissionPoiChainOverlaySoon:noop});
 vm.runInContext(extractOriginalFunction(fs.readFileSync(require.resolve('../app.js'),'utf8'),'applyMissionTargetSceneComposition'),env);
 assert.equal(env.applyMissionTargetSceneComposition({sarScenario:scenario,targetScene:scene}),true);
 assert.equal(md.targetScene.kind,'none');assert.equal(md.missionContract.targetScene.kind,'none');assert.equal(md.missionContract.sarScenario,md.sarScenario);assert.equal(md.sarScenario.scenePlan,scene);assert.equal(w.activeMissionContract.sarScenario.pending,false);
});
